id: P06BF0616
initial_creation_type: ocr
source_metadata:
  work_id: http://purl.bdrc.io/resource/WA1KG1251
  instance_id: http://purl.bdrc.io/resource/IE1KG5397
  collection_id: http://purl.bdrc.io/resource/PR0ET009
  language_id: http://purl.bdrc.io/resource/LangBo
  title:
    bo:
    - བྱ་མགྲིན་སྔོན་ཟླ་བའི་རྟོགས་བརྗོད།
  alt_title:
    zh-latn-pinyin-x-ndia:
    - qing xiang niao de gu shi
  author: http://purl.bdrc.io/resource/P336
  publisher: UCB-OCR
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  volumes:
    94b4a6c2f09c4a15b2f22bccc1314ff6:
      title: པོད ༡་བྱ་མགྲིན་སྔོན་ཟླ་བའི་རྟོགས་བརྗོད
      volume_number: 1
      base_file: UT1KG5397_I1KG5413_0000.txt
      reference: http://purl.bdrc.io/resource/VL3F70F2EE50FBADC2
      image_group: I1KG5413
      quality: Low
  reproductionOf:
  - http://purl.bdrc.io/resource/W1KG5397
  - http://purl.bdrc.io/resource/MW1KG5397
  ocr_software: Namsel
created_at: '2021-12-22T10:49:49.076546'
last_modified_at: '2021-12-22T10:49:49.076552'
